package org.hkprog.m365gui.spoPanel;

import javax.swing.SwingWorker;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.json.JSONArray;
import org.json.JSONObject;
import org.hkprog.m365gui.MainFrame;
import org.hkprog.m365gui.MyLib;

/**
 *
 * @author peter
 */
public class SPOPanel extends javax.swing.JPanel {

	/**
	 * Creates new form SPOPanel
	 */
	public SPOPanel() {
		initComponents();

		// Show loading screen initially
		java.awt.CardLayout cardLayout = (java.awt.CardLayout) getLayout();
		cardLayout.show(this, "loadingCard");

		// Load sites in background
		loadSitesInBackground();
	}

	/**
	 * Loads SPO sites in background and updates the tree
	 */
	private void loadSitesInBackground() {
		SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
			@Override
			protected Void doInBackground() throws Exception {

				try {
					// Get the JSON data from M365 CLI
					String json = MyLib.run(MainFrame.setting.m365Path + " spo site list --output json");

					// Create root node for the tree
					DefaultMutableTreeNode root = new DefaultMutableTreeNode("SharePoint Online Sites");

					if (json != null && !json.trim().isEmpty()) {
						// Parse JSON array
						JSONArray sitesArray = new JSONArray(json);

						// Group sites by template/type for better organization
						DefaultMutableTreeNode teamSites = new DefaultMutableTreeNode("Team Sites");
						DefaultMutableTreeNode communicationSites = new DefaultMutableTreeNode("Communication Sites");
						DefaultMutableTreeNode otherSites = new DefaultMutableTreeNode("Other Sites");

						// Process each site
						for (int i = 0; i < sitesArray.length(); i++) {
							JSONObject site = sitesArray.getJSONObject(i);

							// Extract site information
							String title = site.optString("Title", "Untitled Site");
							String url = site.optString("Url", "");
							String template = site.optString("Template", "");

							// Create a site node with title and URL
							String nodeText = title;
							if (!url.isEmpty()) {
								// Extract site name from URL for cleaner display
								String siteName = url.substring(url.lastIndexOf('/') + 1);
								if (!siteName.isEmpty() && !siteName.equals(title)) {
									nodeText = title + " (" + siteName + ")";
								}
							}

							DefaultMutableTreeNode siteNode = new DefaultMutableTreeNode(nodeText+": "+url);

							// Categorize sites based on template
							if (template.contains("SITEPAGEPUBLISHING")) {
								communicationSites.add(siteNode);
							} else if (template.contains("STS") || template.contains("GROUP")) {
								teamSites.add(siteNode);
							} else {
								otherSites.add(siteNode);
							}
						}

						// Add categories to root (only if they have children)
						if (teamSites.getChildCount() > 0) {
							root.add(teamSites);
						}
						if (communicationSites.getChildCount() > 0) {
							root.add(communicationSites);
						}
						if (otherSites.getChildCount() > 0) {
							root.add(otherSites);
						}
					} else {
						// No sites found or error
						root.add(new DefaultMutableTreeNode("No sites found"));
					}

					// Update the tree model on EDT
					javax.swing.SwingUtilities.invokeLater(() -> {
						jTree1.setModel(new DefaultTreeModel(root));
						// Expand root and first level
						jTree1.expandRow(0);
						for (int i = 1; i < jTree1.getRowCount(); i++) {
							jTree1.expandRow(i);
						}
					});

				} catch (Exception ex) {
					// Handle errors
					DefaultMutableTreeNode root = new DefaultMutableTreeNode("SharePoint Online Sites");
					root.add(new DefaultMutableTreeNode("Error loading sites: " + ex.getMessage()));

					javax.swing.SwingUtilities.invokeLater(() -> {
						jTree1.setModel(new DefaultTreeModel(root));
						jTree1.expandRow(0);
					});
				}
				return null;
			}

			@Override
			protected void done() {
				// Switch to main view after loading
				java.awt.CardLayout cardLayout = (java.awt.CardLayout) getLayout();
				cardLayout.show(SPOPanel.this, "mainCard");
			}
		};
		worker.execute();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Loading");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(704, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        add(jPanel3, "loadingCard");

        jSplitPane1.setDividerLocation(300);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, "mainCard");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
