package org.hkprog.m365gui.commandPanel;

import hk.quantr.javalib.CommonLib;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hkprog.m365gui.MainFrame;

/**
 *
 * @author Peter <peter@quantr.hk>
 */
public class LoginPanel extends javax.swing.JPanel implements CommandPanel {

	String command;

	/**
	 * Creates new form loginPanel
	 */
	public LoginPanel(String command) {
		this.command = command;
		initComponents();
		jLabel1.setText(command);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Kannada MN", 0, 48)); // NOI18N
        jLabel1.setText("m365 login");

        jButton1.setText("Run");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

	@Override
	public String execute() {
		try {
			String str = CommonLib.runCommand(MainFrame.setting.m365Path + " " + command);
			return str;
		} catch (Exception ex) {
			Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
			return ex.getMessage();
		}
	}
}
