package org.hkprog.m365gui.commandPanel;

import hk.quantr.javalib.CommonLib;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.hkprog.m365gui.MainFrame;

/**
 *
 * @author Peter <peter@quantr.hk>
 */
public class ResultPanel extends javax.swing.JPanel implements CommandPanelInterface {

	/**
	 * Creates new form loginPanel
	 */
	public ResultPanel() {
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
	 * Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new java.awt.BorderLayout());

        jTextArea1.setBackground(new java.awt.Color(255, 246, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        add(jTextArea1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

	@Override
	public String execute() {
		try {
			String str = CommonLib.runCommand(MainFrame.setting.m365Path + " tenant info get");
			return str;
		} catch (Exception ex) {
			Logger.getLogger(ResultPanel.class.getName()).log(Level.SEVERE, null, ex);
			return ex.getMessage();
		}
	}
}
